### ISSUE TITLE
Qual o SO

### ISSUE THREAD

**Issue by thiago-viana** [sandrogiacom/cloud-parking#1]
Tudo bem, Sandro?

Tou acompanhando teus vídeos da DIO em que você mostra o desenvolvimento dessa aplicação. Qual foi o sistema operacional que você usou nos vídeos?

Vlw!

**Comment by sandrogiacom** [comment]
Ola Thiago, tudo certo. Eu uso o Linux mint 20 com um tema mac os.

**Comment by thiago-viana** [comment]
Vlw, Sandro. Vou experimentar.
